# Generated by Django 5.0.1 on 2024-02-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_category_alter_item_description_item_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category_id',
            new_name='category',
        ),
    ]
