version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbpy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/scripts/init.sql
