# Generated by Django 5.0.1 on 2024-01-29 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = []
