# Generated by Django 5.0.1 on 2024-01-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_test"),
    ]

    operations = []
