# Generated by Django 5.0.1 on 2024-01-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
