# Generated by Django 5.0.1 on 2024-01-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_test"),
    ]

    operations = []
